language: python

python:
  - 3.6

before_install:
  - pip install -r requirements.txt
  - pip install twine

script:
  - nosetests

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
